### ISSUE TITLE
TeddyBench crashes (uncaught exception) when entering a lower case letter as UID

### ISSUE THREAD

**Issue by gregoreficint** [toniebox-reverse-engineering/teddy#16]
TeddyBench closes because of an uncaught exception if a UID is entered with lower case letters.

Example: 
Try to add a mp3 file with UID e0 04 03 50 12 b1 61 62.

Analysis:
TeddyBench.TeddyMain function EncodeFile(..) has the following line
`Path.Combine(newDir, ReverseUid(uid).Substring(8, 8));` 
that builds the filename with path. It uses ReverseUid with the following code
```
public static string ReverseUid(string uid)
        {
            List<string> groups = (from Match m in Regex.Matches(uid, @"[A-F0-9]{2}") select m.Value).ToList();
            groups.Reverse();
            string ret = string.Join("", groups.ToArray());

            return ret;
        }
```
Here we see the critical part: the regular expression works on upper case UIDs only. Thus, if we enter lower case letters, the string is not correctly parsed and thus, the substring Substring(8,8) that is applied to ReverseUid(uid) throws an OutOfBound Exception. 

Recommended Fixes:
I recommend two fixes. 

First, the code line 
`List<string> groups = (from Match m in Regex.Matches(uid, @"[A-F0-9]{2}") select m.Value).ToList();`
in the function ReverseUid() in MainForm.cs should work with upper case letters
`List<string> groups = (from Match m in Regex.Matches(uid, @"[A-Fa-f0-9]{2}") select m.Value).ToList();`.

Even if this is enough, I like the idea to always take the input of the user id and convert it to upper case so all the methods afterwards use the string in upper case. We achieve this with changing 
`Uid = txtUid.Text` 
in AskUIDForm.cs to
`Uid = txtUid.Text.ToUpper();`

Suggested fixes are available in pull request https://github.com/toniebox-reverse-engineering/teddy/pull/17 .

**Comment by g3gg0** [comment]
weird that i missed that part.
thanks!
