### ISSUE TITLE
TeddyBench 1.2.1 encoded Tonie Files starts always from the begin

### ISSUE THREAD

**Issue by s604k** [toniebox-reverse-engineering/teddy#18]
i recognized that encoded Tonie files with TeddyBench 1.2.1 starts always at the beginnig when put the tag on top of the box. Encoding with Teddy 1.0.1. using -m encode -vbr allows to start at the interupted point.

**Comment by SciLor** [comment]
This isn't a problem with TeddyBench itself. The latest firmware 3.0.8 of the box marks all unknow tags as "hidden" on startup when connected to the Internet. That means they are handled as live tonies, which are always started from the beginning. When the box is online they will even be deleted from the sd http://gt-blog.de/firmware-update-changes-behavior-with-custom-tags/
