### ISSUE TITLE
TeddyBench does not start

### ISSUE THREAD

**Issue by tropappar** [toniebox-reverse-engineering/teddy#21]
I downloaded the latest release (v1.2.2), unzipped, and double clicked on TeddyBench.exe. Nothing happens.
I am using a freshly installed Windows 10.
I tried disabling Windows Defender and excluding the TeddyBench directory from scanning. Did not help.
Is there anything else I need to do?

**Comment by tropappar** [comment]
I also tried installing the .NET framework. Still no luck.

**Comment by AlbrechtL** [comment]
Version 1.2.2 is obviously incomplete. 
```
Unhandled Exception:
System.TypeLoadException: Could not load type of field 'TeddyBench.TeddyMain:TonieInfos' (12) due to: Could not load file or assembly 'TonieAudio, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
[ERROR] FATAL UNHANDLED EXCEPTION: System.TypeLoadException: Could not load type of field 'TeddyBench.TeddyMain:TonieInfos' (12) due to: Could not load file or assembly 'TonieAudio, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
```
You can also see it in the file size of `TeddyBench.exe`
Version 1.2.2: 0,26 MB
Version 1.2.1: 3.6 MB

In my case version 1.2.1 is working.

**Comment by g3gg0** [comment]
oh, sorry. did not realize this issue.
will fix.

**Comment by SciLor** [comment]
I deleted v1.2.2, as v1.2.1 is now fine for virustotal.

https://www.virustotal.com/gui/url/8e5d273edfa1a025a415c3005f444a7176fa0d4de25dea750cad50f5a97c470b/detection
