### ISSUE TITLE
lower case UID leads to exception error

### ISSUE THREAD

**Issue by calipposcout** [toniebox-reverse-engineering/teddy#28]
When using lower case letters when changing the UID, teddybench (ver. 1.2.1) crashes with an Exception error

************** Ausnahmetext **************
System.ArgumentOutOfRangeException: Der Index und die Länge müssen sich auf eine Position in der Zeichenfolge beziehen.
Parametername: length
   bei System.String.Substring(Int32 startIndex, Int32 length)
   bei TeddyBench.TeddyMain.ReassignSelected()
   bei TeddyBench.TeddyMain.lstTonies_DoubleClick(Object sender, EventArgs e)
   bei System.Windows.Forms.Control.OnDoubleClick(EventArgs e)
   bei System.Windows.Forms.ListView.WndProc(Message& m)
   bei System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   bei System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   bei System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by SciLor** [comment]
https://github.com/toniebox-reverse-engineering/teddy/issues/16

Closed the previous issue accidentally. Fix is already integrated into source.
