### ISSUE TITLE
[Windows] Teddy crashed after changing the name of a custom Tag

### ISSUE THREAD

**Issue by JobbeDeluxe** [toniebox-reverse-engineering/teddy#35]
If i change the name of an unknown tag the software crashed.

I build my own form the last source
https://github.com/toniebox-reverse-engineering/teddy/commit/36f5e540d4a30c77aa5af7c96fef98a279c20432

VirtualStudio give me the hint that the error occurs on: 
"CustomTonies.ContainsKey(tag.Hash) the value can not be NULL"

Rename with right click is not working, too.

The rename of an known Tonie and an unknown tonie is working, only custom tags are the Problem right now.

![image](https://user-images.githubusercontent.com/20384365/145088572-732a3558-901e-498f-b220-9eff7ab5d7be.png)

**Comment by g3gg0** [comment]
can you try with the update i just pushed?

**Comment by JobbeDeluxe** [comment]
Last version:
v1.3.0

worked. can be closed. THX for the fix

**Comment by g3gg0** [comment]
👍
