### ISSUE TITLE
Restart from beginning at every contact

### ISSUE THREAD

**Issue by gutschep** [toniebox-reverse-engineering/teddy#39]
Thank you very much for your great tool! I'm using v1.3.3 on Win10.

Unfortunately, my custom Tonie always starts from the very first track - even if there has been no contact to any other Tonie in between. As soon as I remove the Tonie and put it on the TonieBox again, the first audio track starts from the beginning (00:00 min).
In the case of original Tonies, the audio replays from the last played audio track (e.g. 04:37 min).

Is this a user error by myself or expected behavior of the dumped files by TeddyBench?

Thanks very much!

**Comment by tillhanke** [comment]
@gutschep I am experiencing the same behaviour, how did you fix it? Or what was the error?

**Comment by gutschep** [comment]
It's more or less a user error:
If you switch to online mode once, the files for custom tags will be marked hidden by Tonie.
You have to remove the hidden flag of the files on the SD card e.g. in Windows Command Line

cd mydir
attrib -H -S /D /S

Never go online with custom files - you'll have to remove manually the hidden flag again.


On 14 November 2022 10:40:38 CET, tillhanke ***@***.***> wrote:
***@***.*** I am experiencing the same behaviour, how did you fix it? Or what was the error?

**Comment by tillhanke** [comment]
so then you need to put the sd card in without disconnecting the battery, right? because when I reconnect the battery my box ALWAYS boots directly into the online mode... 
But when I exchange the sd card without dis/reconnecting the battery my box just does not recognize the sd. What am I missing? Where am I doing stuff wrong?

**Comment by gutschep** [comment]
Right, you should not disconnect the battery. As you write this would result in going online.

Sometimes I experience myself that the SD card is not recognized. However sometimes it is recognized - I have not found out yet what's different in those situations.
Nevertheless, if the SD is not recognized just wait until the box turns off automatically (something like 5-10 min). When turned on again, the SD is recognized.
That's quite annoying but it worked for me.

**Comment by tillhanke** [comment]
Thanks! I will try that again
