### ISSUE TITLE
laggy behavior while Identification of UID with Proxmark

### ISSUE THREAD

**Issue by Gambrius** [toniebox-reverse-engineering/teddy#4]
Proxmark is kind of laggy, because it is always going through all kind of commands, even if no card is placed onto the Proxmark.

The Process should be
- try to get random number --> until card answers with a random number
- After receiving random number --> Try to read inventory (UID)
- IF card does not answer to INVENTORY command --> Try to deactivate privacy mode with known PWs, (0F or TPW)
- After successful deactivation of privacy mode --> Read UID with INVENTORY command
- After successful read of INVENTORY - continue asking for RANDOM NUMER with SELECT MODE and UID (given by INVENTORY command) --> The random number answer will stop as soon as card is removed from reader
- if card got removed from reader -->start over and just ask for random number

**Comment by g3gg0** [comment]
yep, its just the effort of building the commands and frames which keeps me from doing this ;)

**Comment by Gambrius** [comment]
New process with mentioned proxmark commands works properly (according to Log Window), but UID is not handed over to Window where the UID needs to be entered.

In addittion after successfull deactivation of privacy mode and read of INVENTORY, Proxmark should continue with asking for random number but this time with flag set to SELECTED including the read UID from the INVENTORY command. And than as long as a random number is answered nothing should happend. As soon as no answer is given, it should start again with the GET RANDOM NUMBER like in the beginning of the process..
This process prevents from continous actions on the RFID Chip besides of permanently asking for the RANDOM NUMBER.

**Comment by Gambrius** [comment]
Did test it on the new build.
Works like described. Good job done.

Would close it with new commit.
