### ISSUE TITLE
Leave less sensitive information in decoded files

### ISSUE THREAD

**Issue by steve8x8** [toniebox-reverse-engineering/teddy#60]
I cannot use TeddyBench, so this may already be addressed in the latest code, but Teddy 1.20 writes the full input file path to the decoded .ogg files:
```
$ ogginfo 500304E0-$serial\ -\ Track\ #01.ogg 
Processing file "500304E0-$serial - Track #01.ogg"...

New logical stream (#1, serial: $serial): type opus
Encoded with Lavf58.45.100
User comments section follows...
	encoder=opusenc from opus-tools 0.1.10
	encoder_options=--quiet --bitrate 96 --vbr
	pad=00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
	TeddyVersion=1.2.0-master+49d47dd
	TeddyFile=/Users/.../$id/500304E0
...
```
While this provides useful debugging information, one might want to avoid uploading/sharing such a file since information may be used to identify the tonie and the username.

Also, this part of the information appears to make the resulting files change their size, depending on the actual Teddy invocation. I consider this to be a POLA/POLS violation: decoding the same source file should result in identical output, independent of the input location in the filesystem.

Can addition of this information be made optional?

**Comment by g3gg0** [comment]
privacy issue:
![grafik](https://user-images.githubusercontent.com/479231/214035520-ac4f70eb-c918-4684-8530-51997060d91e.png)

For me personally it is very attractive to see the direct link to the originating tonie file name.
However having the full path can be made optional.

**Comment by steve8x8** [comment]
@g3gg0 I suppose the MessageBox only works in TeddyBench, not pure Teddy, as I never saw it (and there's no hint in the `Teddy.exe -help` output, hint, hint...).
Perhaps I'd be fine with the last directory level and the filename proper ("basename" - that one is obvious anyway), but that still contains the complete identity of the tonie, doesn't it?

**Comment by steve8x8** [comment]
`opus2tonie` seems to do the conversion without adding extra user comments, and it's rather OS-independent, so I will use that for now. (It doesn't have an idea of tonie names, track lists, etc. though.)
