### ISSUE TITLE
TeddyBench does not start when the cfg file is empty

### ISSUE THREAD

**Issue by Gambrius** [toniebox-reverse-engineering/teddy#7]
Due to a crash of TeddyBench I figured out that when the cfg file is left empty, TeddyBench will not start again.
TedyBench should have a failover function, that when the cfg is empty or the content is corrupt, that it will overwrite the cfg with a standard content / configuration.

**Comment by g3gg0** [comment]
i already implemented it that way, both for saving and loading the config.
But seems there is something else.

**Comment by g3gg0** [comment]
JsonConvert does not fail with an exception as expected, but returns a null object when the file is empty.
fixed.
