### ISSUE TITLE
One Teddy max title amount

### ISSUE THREAD

**Issue by sunnyfesh** [toniebox-reverse-engineering/teddy#81]
Hello everyone,

First of all, thank you very much for the great app. I have now been working intensively with it and realized that you can only add a maximum of 100 tracks per teddy. If you use more than 100 tracks, the teddy is generated but not recognized and played on the box. Is this a box or app problem?

**Comment by SciLor** [comment]
This is a technical limit of the box

**Comment by sunnyfesh** [comment]
Ok, thank you very much. Is it possible to limit this in the app? It took me days to figure it out.
