### ISSUE TITLE
Max Volume set via Cloud is ignored

### ISSUE THREAD

**Issue by BOFH90** [toniebox-reverse-engineering/teddy#84]
If i connect the box to the Internet and set a max volume, disable the Internet-Access again and toggle the live-flags on my custom-tags to work again, the max volume does not persist.
Is there any way to limit the Volume and use Custom Tags at the same time?

Thank you

**Comment by SciLor** [comment]
Set the max volume in the cloud, do a freshness check, wait for the box to shut down itself. Then it should be persisted
